### PR TITLE
Update authentication.md

### PR DESCRIPTION
**Pull request by LakshmiLavanyaKasturi**
- Wording changes
- Fixed grammar
- Used simple language
- Changed future tense to present

## Description

Describe the changes that were made in this pull request. When possible start with the motivations behind the change. Be sure to also include the following information:

1. Motivation for change?
2. What was changed?
3. Link to relevant issues?

## Checklist

- [ ] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] New links to files and images were verified
- [ ] For fixes/refactors: all existing references were identified and replaced
- [ ] [Style guide](https://developers.google.com/style) was reviewed and applied
- [ ] Clear code samples were provided
- [ ] People were tagged for review

### CODE REVIEW

**Comment by LakshmiLavanyaKasturi** [comment]
@sabbyanandan: Please review my changes. Thanks.

**Review by sabbyanandan — CHANGES_REQUESTED** [review]
@LakshmiLavanyaKasturi: Another example where we could confirm the screenshots are still correctly presented based on the latest wallet version.

**Comment by LakshmiLavanyaKasturi** [comment]
Sounds like a future work item. Noted. Thanks!

**Comment by LakshmiLavanyaKasturi** [comment]
@sabbyanandan: Do you think we can merge these small changes and I can create an icebox issue to work on screenshot updates?

**Comment by sabbyanandan** [comment]
Probably best to do all the changes together. We can close it for now or refresh it with the screenshots.

**Comment by LakshmiLavanyaKasturi** [comment]
Closing this PR to work on improving and updating the entire document. Icebox issue #116

**Pull request closed without merging**
