### PR TITLE
Update deep-dive-post-conditions.mdx

### PR DESCRIPTION
**Pull request by max-crawford**
I've removed the hyphen from "post conditions" to match the styling of Stacks documentation.

Note: we need to update the sidebar copy as well. Not sure where to do that.

### CODE REVIEW

**Comment by ryanwaits** [comment]
so the official sip uses hyphens when referring to post-conditions throughout, which is why i continued to do so

reference here: https://github.com/stacksgov/sips/blob/main/sips/sip-005/sip-005-blocks-and-transactions.md#transaction-post-conditions

happy to hear others weigh in though @janniks

**Comment by janniks** [comment]
Happy to do whatever is most official 🤷🏼‍♀️ SIP is good; Stacks Docs does it without hyphens. No strong opinion on my part

**Comment by max-crawford** [comment]
Oh I didn't realize the SIP used the hyphen. I was matching what I saw here: https://docs.stacks.co/stacks-101/post-conditions

I don't feel strongly about this. My sense is that more people will read Stacks docs than the SIP, so having uniformity between our docs and theirs would be beneficial, but I see the argument for keeping it as well.

**Comment by ryanwaits** [comment]
closing this for now

**Pull request closed without merging**
