### PR TITLE
chore: add url checker #54

### PR DESCRIPTION
**Pull request by randr000**
## Description

The changes specified in the issue were made.

- markdown-link-check was added as a dev dependency
- mlc_config.json file was added
- urlcheck script was added to package.json

I also attached the results of running urlcheck.

[broken_links.txt](https://github.com/hirosystems/docs/files/8836263/broken_links.txt)

## Checklist

- [x] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] New links to files and images were verified
- [x] For fixes/refactors: all existing references were identified and replaced
- [x] [Style guide](https://developers.google.com/style) was reviewed and applied
- [x] Clear code samples were provided
- [x] People were tagged for review
@agraebe

### CODE REVIEW

**Comment by sabbyanandan** [comment]
Hi, @randr000. Thank you for this PR! I see a few 404s that aren't directly associated with the source files, though. Unclear how they manifest as broken URLs - you may have some details to share given your familiarity with `markdown-link-check`. Any education helps.

Examples:
> 26 links checked.
  [✖] https://stacks.js.org/classes/auth.usersession.html → Status: 404
  [✖] https://stacks.js.org/classes/auth.appconfig.html → Status: 404
  [✖] https://docs.stacks.co/references/bns → Status: 404
  [✖] https://stacks.js.org/classes/storage.storage-1.html#putfile → Status: 404
  [✖] https://stacks.js.org/classes/storage.storage-1.html#getfile → Status: 404
  [✖] https://stacks.js.org/classes/auth.usersession.html#signuserout → Status: 404

**Comment by sabbyanandan** [comment]
Relates to #54

**Comment by sabbyanandan** [comment]
Thank you, @randr000. Those URLs fail to resolve, but they aren't directly embedded in our docs source code, so that was the confusion I had. I could be misinterpreting, though.

@janniks or @LakshmiLavanyaKasturi: Do you have any other feedback on this approach? If you're comfortable taking this extra dependency in the build path, this would be an incredible value add!

**Comment by janniks** [comment]
_Updated most of them in: https://github.com/hirosystems/docs/pull/115_

🎉 Yea, I welcome the idea of checking for broken links (ideally we would add this to a github action on pull_request)

**Comment by LakshmiLavanyaKasturi** [comment]
> Thank you, @randr000. Those URLs fail to resolve, but they aren't directly embedded in our docs source code, so that was the confusion I had. I could be misinterpreting, though.
> 
> @janniks or @LakshmiLavanyaKasturi: Do you have any other feedback on this approach? If you're comfortable taking this extra dependency in the build path, this would be an incredible value add!

I definitely like the approach.  

> Thank you, @randr000. Those URLs fail to resolve, but they aren't directly embedded in our docs source code, so that was the confusion I had. I could be misinterpreting, though.
> 
> @janniks or @LakshmiLavanyaKasturi: Do you have any other feedback on this approach? If you're comfortable taking this extra dependency in the build path, this would be an incredible value add!

Sounds like a great value add. I would love to do that. Let me figure out a way to do md -> html.

**Comment by janniks** [comment]
Closed in favor of #123 ; Thanks for the PR 🙏 We now integrated the used tool into our CI

**Pull request closed without merging**
