### PR TITLE
Docs| Logo and Favicon updates #154

### PR DESCRIPTION
**Pull request by LakshmiLavanyaKasturi**
Updated Hiro Logo and Favicon for Hiro-docs.   

    Modified files:
     
        modified:   docusaurus.config.js
        modified:   static/img/favicon.ico

     Deleted files: 
     
        deleted:    static/img/footer-logo-dark.svg
        deleted:    static/img/footer-logo-light.svg
        deleted:    static/img/logo-dark.svg
        deleted:    static/img/logo-light.svg
       
     Files added:

        new file:   static/img/hiro-docs-footer.svg
        new file:   static/img/hiro-docs-logo.svg

### CODE REVIEW

**Review by sabbyanandan — CHANGES_REQUESTED** [review]
@eugeniadigon: In the default mode, the logo looks good, but when toggling to the dark, the logo blends-in with the header. See:

image
 
 Any recommendations?

**Comment by janniks** [comment]
Screen Shot 2022-09-21 at 16 50 47
We'll need a dark mode version of the `docs` logo.

---

Screen Shot 2022-09-21 at 16 50 32
It feels like the `footer` logo should be a bit smaller.

**Comment by eugeniadigon** [comment]
hirodocs-light
 Light version here

**Comment by janniks** [comment]
I liked the vibe of the old footer.
Screen Shot 2022-09-21 at 17 00 49

Here's a .png of the new Hiro icon rounded-white in a similar size: https://we.tl/t-hFnxhvY3oM

**Comment by eugeniadigon** [comment]
Thank you @janniks :') 

Here's the same but on neutral colors and in SVG, in case the sizing needs to be fixed
hirodocs-footer

**Comment by LakshmiLavanyaKasturi** [comment]
@janniks @sabbyanandan @eugeniadigon: Please let me know if the changes look good. Thanks!

**Review by janniks — APPROVED** [review]
I think this is a good start. We can add more orange 🍊 later on.

**Review by sabbyanandan — APPROVED** [review]
Let's go!

**Pull request merged**
