### PR TITLE
feat: clarity documentation

### PR DESCRIPTION
**Pull request by ryanwaits**
## What does this PR do?

This PR introduces a new initiative in our documentation that emphasizes the why and when behind using specific Clarity functions, alongside real-world blockchain use cases.

Each section explains relevant use cases, discusses the significance of the functions, and includes code samples to illustrate their implementation, along with best practices and common patterns.

- [x] Each function documents
- [x] A few additional guides for basic arithmetic, access control, and handling optionals and errors

### CODE REVIEW

**Comment by max-crawford** [comment]
On the overview page for Clarity, in the Function categories cards, the cryptographic functions and the time-based logic cards have broken sidebars. Once I click into those guides, the left hand side shows Bitcoin, guides, and stacks.

These pages should just show the Clarity side bar.

Also on the note of the sidebar, should these 4 guides be linked there under Advanced or below introduction?

**Comment by ryanwaits** [comment]
> Once I click into those guides, the left hand side shows Bitcoin, guides, and stacks.

ah good catch - those were meant to be hidden (as you can see they don't appear on the sidebar). I forgot about the cards on the intro page that link to them. I've updated the intro page to not link to these guides since they are not complete.

> Also on the note of the sidebar, should these 4 guides be linked there under Advanced or below introduction?

I updated that section to be a **Guides** section, and sit above the **Functions** section.

**Review by max-crawford — APPROVED** [review]
Made some tweaks. Still want to do a copy pass on the individual functions, but that is not a blocker to getting this live in prod. Approved!

**Review by ECBSJ — APPROVED** [review]
lgtm

**Pull request merged**
