### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by janniks**
- update to latest deps (eg docusaurus)
- add latest cli reference

### CODE REVIEW

**Comment by sabbyanandan** [comment]
@janniks: I get this on the `update-deps` branch with `yarn build`:

```
╰─$ yarn build
yarn run v1.22.17
warning package.json: No license field
$ yarn update:cli-ref && docusaurus build
warning package.json: No license field
$ stx docs > src/_data/cli-reference.json && node ./update-cli-ref.js ./src/_data/cli-reference.json -o ./docs/references/
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'yargs/yargs'
Require stack:
- /Users/sabbyanandan/Downloads/pr-folder/docs/update-cli-ref.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/sabbyanandan/Downloads/pr-folder/docs/update-cli-ref.js:14:12)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/sabbyanandan/Downloads/pr-folder/docs/update-cli-ref.js' ]
}

Node.js v17.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

Anything jumps out to you?

**Comment by sabbyanandan** [comment]
I tried cleaning up the cache via `npm cache` and by rerunning `npm install`, made the situation even worse. 😆

**Comment by janniks** [comment]
Checked again, works for me (and also in Vercel/Netlify)

- You can try cleaning `git clean -id` the repo
- Then install packages with plain `yarn`
- Then `yarn build` should work
  - After which the `build` dir was generate and could be previewed with `yarn serve`

**Comment by sabbyanandan** [comment]
Good, that helped. Thanks.

**Comment by sabbyanandan** [comment]
@trichards-hiro @LakshmiLavanyaKasturi: This PR upgrades the dependency versions, and in my view, it is probably better to get this merged before your re-org PRs. WDYT?

**Comment by trichards-hiro** [comment]
@sabbyanandan I agree...let's merge this before we begin adding our new nav structure.

**Comment by LakshmiLavanyaKasturi** [comment]
> @trichards-hiro @LakshmiLavanyaKasturi: This PR upgrades the dependency versions, and in my view, it is probably better to get this merged before your re-org PRs. WDYT?

Agreed!

**Pull request merged**
