### PR TITLE
Add developer survey CTA

### PR DESCRIPTION
**Pull request by sabbyanandan**

### CODE REVIEW

**Comment by sabbyanandan** [comment]
@eugeniadigon: If the RGB variants on the button is incorrect, please let me know. Happy to fix that.

@bmfranklin @max-crawford: Here's a preview: https://deploy-preview-348--hiro-docs.netlify.app/ — if you both and @eugeniadigon are good with it, please feel free to merge.

**Comment by LakshmiLavanyaKasturi** [comment]
I'm unable to select the scale to rate from 1 to 10. 1 and 2 are selectable but help navigate between the first and second pages. Am I missing something here? @sabbyanandan

**Comment by eugeniadigon** [comment]
I think we can certainly do better if we really want to drive users to take the survey. I'm not sure a mysterious button that only says "take the dev survey" will help (I could be wrong though).

Isn't there a way to add a marquee banner for that? (like in hiro.so)
Or, something like this would be great:
Screenshot 2023-05-08 at 18 47 47

**Comment by eugeniadigon** [comment]
I still advise against the button. We should aim to try and give the best possible experience, especially in a place like Docs, especially us, being a dev company. Is really the only possible option?

**Pull request merged**
