### PR TITLE
Updated docs landing page description

### PR DESCRIPTION
**Pull request by LakshmiLavanyaKasturi**
Updated landing page description.

### CODE REVIEW

**Comment by eugeniadigon** [comment]
@max-crawford Would you mind helping here?

**Comment by max-crawford** [comment]
My instinct here would be to reorient the link text around what the user accomplishes, not the name of the tool. So the tile would look something like:

### Get started

Accelerate your Web3 development with the following:

[Web-hosted contract development](https://platform.hiro.so)
[JS Client for the Stacks Blockchain API]([Stacks Blockchain API Client](https://hirosystems.github.io/stacks-blockchain-api/client/))
[JavaScript project templates](https://docs.hiro.so/stacksjs-starters)

Thoughts? @eugeniadigon @LakshmiLavanyaKasturi

**Comment by eugeniadigon** [comment]
I like relating it to goals/what it accomplishes. This was also in the example mock up (just sharing to see different ideas):

Screenshot 2023-07-25 at 21 05 01

I'm not sure I've got the right answer for this. This is probably part of our opinionated user flows project still WIP. Would love to hear @bmfranklin thoughts as well

**Comment by bmfranklin** [comment]
Agreed with Max, it feels more intuitive for the developer. @eugeniadigon did you need help with lines for specific products? How can I best help?

**Comment by eugeniadigon** [comment]
I guess I would like to aim for something that sounds a bit less marketing-ish. "Accelerate your Web3 development" could be 
a great tagline for someone _before_ entering Docs, but now that we're here, perhaps something that sounds more concrete and action-oriented could be clearer. I don't have the technical knowledge to propose something here, but what's the ABC or 3 first actions that a developer should do first? 1) Set up Clarinet 2) Create and test contract in Platform 3) Get familiar with the Stacks.js library (for example). So what could be the subtext accompanying this? 

**Get started**
Develop and test your first smart contract in minutes by following these useful links:
or
Develop your decentralized app. Start with these:

(These are just suggestions of course)

**Comment by LakshmiLavanyaKasturi** [comment]
@ginny @max-crawford @bmfranklin Please let me know if the latest changes look good to you. 
@sabbyanandan FYI.

**Comment by eugeniadigon** [comment]
@LakshmiLavanyaKasturi , Product Marketing will come up with a recommendation shortly, please await for their input. Thank you

**Comment by elenananana** [comment]
Does the **Get Started** block need links? As a user, I feel like there are a lot of things to click on. I have the side panel, the popular topics, those are really big and draw my attention. Would it be possible to simply make the popular topics the first three places to get started? Here's some recommendations along with screen shots of other docs landing pages for comparison.

[Notion](https://www.notion.so/hiropbc/Docs-Getting-Started-Notes-1c835ca4a2274767806a1bc8c8b06771?pvs=4)

### Start building on Bitcoin Layers

Option 1

Explore API references, feature guides and tutorials to integrate Stacks and Ordinals into your application. Start here:

Option 2
Integrate Stacks and Ordinals in your application with Hiro’s tools. Explore API references, feature guides and tutorials.

**Comment by eugeniadigon** [comment]
I would do:

### Start building on Bitcoin Layers
Explore API references, feature guides, and tutorials to integrate Stacks and Ordinals into your application. Start here:
- [Stacks Blockchain API Client](https://hirosystems.github.io/stacks-blockchain-api/client/)
- [Stacks.js starters](https://docs.hiro.so/stacksjs-starters)
- [Sign in to Hiro Platform] (https://platform.hiro.so)

**Comment by LakshmiLavanyaKasturi** [comment]
> I would do:
> 
> ### Start building on Bitcoin Layers
> Explore API references, feature guides, and tutorials to integrate Stacks and Ordinals into your application. Start here:
> 
> * [Stacks Blockchain API Client](https://hirosystems.github.io/stacks-blockchain-api/client/)
> * [Stacks.js starters](https://docs.hiro.so/stacksjs-starters)
> * [Sign in to Hiro Platform] (https://platform.hiro.so)

This sounds good to me.  I will update the PR.

**Comment by LakshmiLavanyaKasturi** [comment]
Closing this PR as there are multiple conflicts with the docusaurus config file. Addressing this issue in https://github.com/hirosystems/docs/pull/441.

**Pull request closed without merging**
