### PR TITLE
Update managing-accounts.md

### PR DESCRIPTION
**Pull request by LakshmiLavanyaKasturi**
- Syntax changes to Note and Info to make it more noticeable.
- Wording changes for clarity
- Added details for context

### CODE REVIEW

**Comment by LakshmiLavanyaKasturi** [comment]
@sabbyanandan: Please review my changes. Thanks.

**Comment by LakshmiLavanyaKasturi** [comment]
@sabbyanandan Can you please approve these small wording changes? Thanks.

**Comment by sabbyanandan** [comment]
Same as https://github.com/hirosystems/docs/issues/78; if we can make sure this tutorial works in its current form, let's please merge it. Otherwise, I would refresh this PR with functional steps.

**Comment by LakshmiLavanyaKasturi** [comment]
Closing this PR to work on refreshing the document in #78.

**Pull request closed without merging**
