### PR TITLE
Docs/clarinet js sdk

### PR DESCRIPTION
**Pull request by ryanwaits**
## Description

Update docs to include latest Clarinet JS SDK

- [x] Remove old references to `Clarinet` docs, and add new ones for `Clarinet JS SDK`

### CODE REVIEW

**Review by sabbyanandan — CHANGES_REQUESTED** [review]
The changes in this PR looks straightforward, but the content itself needs more fleshing out. 

I left a highl-level commentary and can be found in vercel preview: 
https://vercel.live/link/hiro-systems-docs-git-docs-clarinet-js-sdk-blockstack.vercel.app?page=%2Fclarinet%2Ffeature-guides%2Fclarinet-js-sdk%3FvercelThreadId%3DnPxxb&via=in-app-copy-link

https://vercel.live/link/hiro-systems-docs-git-docs-clarinet-js-sdk-blockstack.vercel.app?page=%2Fclarinet%2Ffeature-guides%2Ftest-contract-with-clarinet-sdk%3FvercelThreadId%3DXxErU&via=in-app-copy-link

**Comment by sabbyanandan** [comment]
In case you aren't able to see the threads in Vercel; here's an example (so look for these bubbles):
image

**Comment by sabbyanandan** [comment]
Since you do not have access, here is the 2nd and the last comment in Vercel: 
image

**Comment by ryanwaits** [comment]
updates here awaiting review: [Clarinet PR #1185](https://github.com/hirosystems/clarinet/pull/1185)

**Review by hugocaillard — APPROVED** [review]
LGTM

**Pull request merged**
